### ISSUE TITLE
GRATZ!

### ISSUE THREAD

**Issue by dove-zp** [L-Spiro/MhsX#3]
Glad to see you finally finished and released the source for your new version of MHS! I've been wanting to see it for some years! The tools you included are very handy - esp the floating-point studio. Thank you very much for making it open source! It has some bugs but overall it is very helpful when it comes to variable data manipulation and variable structure analysis.

**Comment by L-Spiro** [comment]
I’m unaware of any bugs in MHS X, but I am very aware that it is extremely unfinished!  All features that have been implemented should be fully working and completely stable, but there are many many features that are simply not implemented yet.
