### ISSUE TITLE
Linux operating system

### ISSUE THREAD

**Issue by AzuosShazous** [L-Spiro/MhsX#6]
Is there a possibility of creating a version for Linux?

**Comment by L-Spiro** [comment]
I’m not sure such a thing is possible.  This uses features such as `::ReadProcessMemory()` and many others that are available only on Windows.  If anything were to be made on Linux, it would have to be some kind of from-scratch port, and I’m not the one who would be able to do it.  Debuggers and investigation tools such as this are typically platform-specific, but someone could try in the future.
At the very least, some of the most critical and hardest-to-code systems are platform-agnostic, such as the Expression Evaluator, which will compile on any platform.  A lot of individual components can be ported to all platforms, but the whole package would be a challenge.

**Comment by AzuosShazous** [comment]
I understand your answer. Well, I use scanmem and gameconqueror to map certain memory addresses, but I need a 32-bit utility to access specific floating addresses. Anyway, thanks.

**Comment by AzuosShazous** [comment]
Thank you very much for your time.
